### ISSUE TITLE
Plugin uses ES6 syntax when installed

### ISSUE THREAD

**Issue by frederikschubert** [mobilexag/plugin-sass#25]
After installing this plugin via `jspm install scss=sass` the import of the plugin fails because it uses ES6 syntax.
```
plugin-sass@0.2.0.js:1 Uncaught SyntaxError: Unexpected token export
...
```
I am using this [plugin](https://github.com/frankwallis/plugin-typescript/) to transpile my TypeScript code to ES5 but I did not manage to configure it in a way to also transpile plugin-sass.

**Comment by frederikschubert** [comment]
So what I am basically asking for would be an es5 transpiled build of the plugin in the npm distribution. :)

**Comment by screendriver** [comment]
Unfortunately I don't have any experience with TypeScript or any other transpilers than Babel. So I don't know how solve this directly. One solution would be to distribute only ES5 code but therefore I have to change package. Maybe there is an jspm / SystemJS API for that but I only know [this](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md) documentation. The whole SystemJS thing is build around ES6 / ES2015. Maybe someone other than me can help here?

> So what I am basically asking for would be an es5 transpiled build of the plugin in the npm distribution. :)

There is no npm distribution. The plugin is installed directly from GitHub.

**Comment by frederikschubert** [comment]
Thank you for your response! I will try if it is possible to use the typescript and babel transpilers together, to solve this problem. If that doesn't work I will open an issue at the SystemJS repo.

**Comment by screendriver** [comment]
:+1:

**Comment by peterjuras** [comment]
You are probably running into this issue because you set the jspm property 'transpiler' to not use a transpiler (i.e. false). This means that not even the modules inside jspm_packages will be compiled and that is why you get the Unexpected token error. Most modules that are meant to be used with jspm/systemjs are written in ES6, so setting transpiler to false will not work in most cases.

An easy solution is to set the jspm transpiler to babel. Your TypeScript files will remain untouched, because they are loaded by the typescript-plugin and will be skipped by the compiler.

I created a [sample project](https://github.com/peterjuras/sample-jspm-ts-sass) in which you can see a working configuration example. Try setting the transpiler to 'false' and you will see the error you mentioned. When you leave the default transpiler as babel, everything should work fine.

**Comment by frederikschubert** [comment]
Ok I see. Thank you for your support! This solution works for me.
