### ISSUE TITLE
Configuration via System.config

### ISSUE THREAD

**Issue by frederikschubert** [mobilexag/plugin-sass#37]
To have a good modularization in our project we currently add our project root directory to the includePaths property of the sass compiler options.
This way we can place a variables and mixins file in a specific place in our app and import it in all submodules relative to the project root.
I would like to switch from our gulp based transpile-and-copy workflow to your plugin. For the above to work I would need to pass some options to the sass compiler in your plugin. Would this be possible to integrate?

**Comment by screendriver** [comment]
I don't know if this is possible. The only thing I know is that you can import plugins with a `!` like `import 'some/data.json!';`. But how you can pass arguments to that is a thing I don't know. You should open a new issue at [SystemJS](https://github.com/systemjs/systemjs) and reference to this issue here. Maybe [Guy Bedford](https://github.com/guybedford) know a solution for that.

**Comment by frederikschubert** [comment]
I think it should be possible as plugin-typescript does the same thing with its System.config.typescriptOptions.

**Comment by screendriver** [comment]
Ok I can see it. What options would you like to see in the config settings? I am thinking about to add something like this to my `config.js`:

```js
System.config({
  sassOptions: {
  }
});
```

**Comment by rosshinkley** [comment]
+1 for `sassOptions`.  Include paths are a must.

@screendriver Are you actively working on this?  Would a PR that implements `sassOptions` be helpful?

**Comment by rosshinkley** [comment]
I spent a little time with this tonight and have some questions about injecting Sass at runtime.  (I haven't had a chance to look at bundling yet.)

I could get `plugin-sass` to preload imported files with [`lazyFiles`](https://github.com/medialize/sass.js/#working-with-files), but since the file load takes place in the browser, it has the drawback of having to provide a complete manifest of every file that might be imported.  (Globbing isn't possible over HTTP out of the box.)

I'm considering amending the import override to look at the directories specified in the `includePaths`, but I'm fearful this will have nasty performance consequences.  This also doesn't fully resolve the above complete manifest issue as all subdirectories will also have to be explicitly listed.

I suppose the files could be globbed in a Gulp task and added to a special collection in the configuration, but that also feels improper to me.

I'm a bit at a loss as which option is best.  I also feel like there must be a better, simpler way of accomplishing this without a precompile.

Thoughts?

**Comment by screendriver** [comment]
> @screendriver Are you actively working on this? Would a PR that implements sassOptions be helpful?

The next features I am working on is to optionally disable autoprefixer and include sassOptions in a configuration file.

I am not experienced enough to use `lazyFiles`. I am using the loading mechanism of SystemJS. So I don't know if it's working what you trying to use. But Sass injection at runtime (`sass-inject`) is **only** meant for development time. For production you have to use the bundling mechanism from jspm. At bundling time **all** transpiled SASS files will directly included in your `bundle.js` file so there is no need for `lazyFiles`.

**Comment by rosshinkley** [comment]
@screendriver I think I should have been more clear about the use case I was trying to address.  I wanted to use `sass-plugin` at runtime for development, but could not as some of the resources required to compile the sass sheet were located outside of the project.

As I understand it (and it is _completely_ possible I'm wrong), `sass-inject` is run entirely in the browser, and as such, the referenced paths for local files in this situation will not work.  To address that, the file listing would need to be to valid HTTP endpoints.  Since HTTP doesn't support globbing, I don't think you could get away with specifying a base path only and hoping the child paths resolve.  This means that you'd end up specifying _every_ valid sheet and partial URI path in `includePaths`.  While technically valid, it's not very pretty, and can (and probably will) lead to maintainability problems.  Furthermore, those endpoints would have to be available at bundle-time, and there's no guarantee they will be.

As I read @frederikschubert's original post, I took it as wanting to use `plugin-sass` at development time as well as production bundling, and after reading your comments, I'm beginning to think that maybe I misunderstood the original intent.  Won't using `sass-builder` and the JSPM bundler lead to the problems that @frederikschubert was trying to avoid, specifically the "gulp based transpile-and-copy workflow" at development time?

**Comment by screendriver** [comment]
Done. Please let me know if anything is missing or not working.

@rosshinkley for SystemJS you don't need Gulp tasks that concat / minify and uglify your code. Everything is already there and shipped with jspm.
