### ISSUE TITLE
Error loading traceur with jspm 0.17.0-beta.14

### ISSUE THREAD

**Issue by ettoredn** [mobilexag/plugin-sass#57]
I'm trying to use the plugin with jspm 0.17.0-beta.14, however when loading the app it throws an error related to traceur.
In order to replicate the issue:
`git clone git@github.com:ettoredn/jspm-scss-test.git && cd jspm-scss-test`
`npm install`
`jspm install`
`npm start`

![screen shot 2016-04-30 at 01 54 49](https://cloud.githubusercontent.com/assets/739903/14932457/9becfee8-0e76-11e6-9534-f1596845e98c.png)

By commeting jspm-sass.js:1 the app works fine.

**Comment by screendriver** [comment]
You are using jspm@0.17.0-beta.14 which is not a stable release. It is still a beta and has bugs. Especially for plugins. Please use the latest stable version.

Unfortunately I don't have any experience with Traceur. `jspm` and `SystemJS` are primary made for the Babel transpiler. There are a lot of issues related to yours. The only difference is that they are using TypeScript instead of Traceur (#51, #55, #43, #35...). The solution for that is in issue #25. It should work for Traceur als well.

Please let me know if your problem is solved with the jspm stable release [0.16.34](https://www.npmjs.com/package/jspm) and the workaround mentioned in issue #25.
